// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.2
// source: driveservice/service.proto

package driveservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SuccessMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *SuccessMessage) Reset() {
	*x = SuccessMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_driveservice_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuccessMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessMessage) ProtoMessage() {}

func (x *SuccessMessage) ProtoReflect() protoreflect.Message {
	mi := &file_driveservice_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessMessage.ProtoReflect.Descriptor instead.
func (*SuccessMessage) Descriptor() ([]byte, []int) {
	return file_driveservice_service_proto_rawDescGZIP(), []int{0}
}

func (x *SuccessMessage) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_driveservice_service_proto protoreflect.FileDescriptor

var file_driveservice_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x64, 0x72, 0x69, 0x76, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x64, 0x72,
	0x69, 0x76, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20, 0x0a, 0x0e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x32, 0xaa, 0x01, 0x0a, 0x0c, 0x44, 0x72, 0x69,
	0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x09, 0x46, 0x69, 0x6c,
	0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x09, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x1a, 0x0a, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12,
	0x25, 0x0a, 0x06, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x0e, 0x2e, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x25, 0x0a, 0x08, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x09, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0c, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x12, 0x26, 0x0a,
	0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x09, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x1a, 0x0f, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x64, 0x72, 0x69, 0x76, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_driveservice_service_proto_rawDescOnce sync.Once
	file_driveservice_service_proto_rawDescData = file_driveservice_service_proto_rawDesc
)

func file_driveservice_service_proto_rawDescGZIP() []byte {
	file_driveservice_service_proto_rawDescOnce.Do(func() {
		file_driveservice_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_driveservice_service_proto_rawDescData)
	})
	return file_driveservice_service_proto_rawDescData
}

var file_driveservice_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_driveservice_service_proto_goTypes = []any{
	(*SuccessMessage)(nil), // 0: SuccessMessage
	(*FileInfo)(nil),       // 1: FileInfo
	(*UploadRequest)(nil),  // 2: UploadRequest
	(*FilesInfo)(nil),      // 3: FilesInfo
	(*FileContent)(nil),    // 4: FileContent
}
var file_driveservice_service_proto_depIdxs = []int32{
	1, // 0: DriveService.FilesList:input_type -> FileInfo
	2, // 1: DriveService.Upload:input_type -> UploadRequest
	1, // 2: DriveService.Download:input_type -> FileInfo
	1, // 3: DriveService.Delete:input_type -> FileInfo
	3, // 4: DriveService.FilesList:output_type -> FilesInfo
	1, // 5: DriveService.Upload:output_type -> FileInfo
	4, // 6: DriveService.Download:output_type -> FileContent
	0, // 7: DriveService.Delete:output_type -> SuccessMessage
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_driveservice_service_proto_init() }
func file_driveservice_service_proto_init() {
	if File_driveservice_service_proto != nil {
		return
	}
	file_driveservice_files_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_driveservice_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SuccessMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_driveservice_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_driveservice_service_proto_goTypes,
		DependencyIndexes: file_driveservice_service_proto_depIdxs,
		MessageInfos:      file_driveservice_service_proto_msgTypes,
	}.Build()
	File_driveservice_service_proto = out.File
	file_driveservice_service_proto_rawDesc = nil
	file_driveservice_service_proto_goTypes = nil
	file_driveservice_service_proto_depIdxs = nil
}
